kind: Node
apiVersion: v1
metadata:
  name: ip-10-0-131-14.ec2.internal
  labels:
    disk: ssd

---------------

apiVersion: v1
kind: Pod
metadata:
  name: nginx
  labels:
    app: MyApp
spec:
  nodeSelector:
    disk: ssd
  containers:
  - name: nginx
    image: nginx:1.14.2
    ports:
    - containerPort: 80

-------------------

apiVersion: v1
kind: Service
metadata:
  name: my-service
spec:
  type: NodePort
  selector:
    app: MyApp
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30007
